### ISSUE TITLE
[BUG] Tasker integration: SET_TUNEL_DOWN doesn't work 

### ISSUE THREAD

**Issue by danielzfranklin** [msfjarvis/viscerion#184] opened 2019-10-10 04:04 UTC
**Describe the bug**
I successfully used a tasker action to start a VPN connection. I copied that action and changed the action to `Me.msfjarvis.viscerion.SET_TUNNEL_DOWN`. When I run that action, nothing happens. I've run the action manually to make sure the issue isn't with the trigger. The tasker logs reads that the intent was sent successfully. 

**To Reproduce**
1. Enter the following information (2 pictures) 
![obscura1570679937523](https://user-images.githubusercontent.com/10361846/66538082-ec5bca80-eaf0-11e9-9ba3-41c00139b006.jpg)
![obscura1570679988558](https://user-images.githubusercontent.com/10361846/66538090-f1207e80-eaf0-11e9-89a5-432e3939bfe7.jpg)

2. Run the action (picture) 
![Screenshot_20191010-000048](https://user-images.githubusercontent.com/10361846/66538141-21681d00-eaf1-11e9-8c95-c50d987e8d54.png) 

**Expected behavior**
Key icon indicating active VPN connection in status bar disappears, indicating VPN disconnected. 

**Device information (please complete the following information):**
 - Device: Google Pixel 2
 - OS: stock ROM Android version 10 (Sept 2019 security patch level) 
 - Backend: Tasker
 - Version 5.1.1

**Comment by msfjarvis** [comment] 2019-10-10 05:03
Thanks for the detailed report. This is a duplicate of #149 so I'm gonna continue tracking this there.

**Closed by msfjarvis** 2019-10-10 05:03 UTC
Labels: bug
