### ISSUE TITLE
[BUG] The application crashes when i try to open the application 

### ISSUE THREAD

**Issue by friendsmobile** [msfjarvis/viscerion#154] opened 2019-07-26 10:35 UTC
# Project Information

* Repository:  https://github.com/MSF-Jarvis/viscerion
* Project Name:  Viscerion
* My Github Account: https://github.com/friendsmobile
* Download the application:   [HERE](https://play.google.com/store/apps/details?id=me.msfjarvis.viscerion&utm_source=GitHub&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1)

# Expected behavior

When I try to open the application, the application should be open and all the options contained in it should be displayed so that users can easily get the most out of these options.

# Actual behavior

When I try to open the application, the application crashes

#### How to reproduce

* [Download ](https://play.google.com/store/apps/details?id=me.msfjarvis.viscerion&utm_source=GitHub&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1)the application
*  try to open the Application
* Note the Error

* Browser/App version:  Current Version 5.1.1
* Operating system: 6.0

#### Recording Of The Bug

![20190726_152705](https://user-images.githubusercontent.com/51118734/61945751-a6618280-af55-11e9-8ebb-b65a6a49ceca.gif)

#### Logcat

<pre><code>D/AndroidRuntime(27294): Shutting down VM

E/AndroidRuntime(27294): FATAL EXCEPTION: main

E/AndroidRuntime(27294): Process: me.msfjarvis.viscerion, PID: 27294

E/AndroidRuntime(27294): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.res.Resources.getAssets()' on a null object reference

E/AndroidRuntime(27294): 	at android.app.LoadedApk.getAssets(LoadedApk.java:582)

E/AndroidRuntime(27294): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:649)

E/AndroidRuntime(27294): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4964)

E/AndroidRuntime(27294): 	at android.app.ActivityThread.access$1600(ActivityThread.java:177)

E/AndroidRuntime(27294): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1491)

E/AndroidRuntime(27294): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(27294): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(27294): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(27294): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(27294): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(27294): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(27294): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by MSF-Jarvis** [comment] 2019-07-26 13:47
Can you send the unfiltered log? From this snippet it looks like it's a bug in your device's ROM.

**Comment by friendsmobile** [comment] 2019-07-27 06:22
@MSF-Jarvis  how can i find   unfiltered log I am not a programmer

**Comment by MSF-Jarvis** [comment] 2019-07-27 09:04
Just type `adb logcat -c > logcat.txt` in a command prompt/terminal and then open the app. Once it crashes, close the terminal and send the logcat.txt file here.

**Comment by msfjarvis** [comment] 2019-07-29 08:21
gentle ping @friendsmobile :)

**Comment by friendsmobile** [comment] 2019-07-29 08:50
I don,t know what happened with your application now the bug has been solved automatically

**Comment by msfjarvis** [comment] 2019-07-29 09:55
Alright, I'll close this then, please re-open if you can reproduce it reliably.

**Comment by friendsmobile** [comment] 2019-07-29 09:56
ok dear

**Closed by msfjarvis** 2019-07-29 09:55 UTC
Labels: bug
